//! `PGRD` — a cell path grid.

use crate::types::latin1::L1Str;
use crate::esm::common::{
    Subrecord, l1, finish, le_i32, le_u16, le_u32, le_u8, parse_or_default,
};
use nom::multi::many0;
use nom::{IResult, Parser};

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct PathGridData {
    /// Grid coordinates (exterior cells only).
    pub grid_x: i32,
    pub grid_y: i32,
    pub flags: u16,
    pub point_count: u16,
}

fn path_grid_data(input: &[u8]) -> IResult<&[u8], PathGridData> {
    let (input, grid_x) = le_i32(input)?;
    let (input, grid_y) = le_i32(input)?;
    let (input, flags) = le_u16(input)?;
    let (input, point_count) = le_u16(input)?;
    Ok((
        input,
        PathGridData {
            grid_x,
            grid_y,
            flags,
            point_count,
        },
    ))
}

/// A single path grid node (16 bytes within `PGRP`).
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct PathPoint {
    pub x: i32,
    pub y: i32,
    pub z: i32,
    /// `0x1` = autogenerated.
    pub flags: u8,
    /// Number of outgoing edges (entries in `PGRC` for this point).
    pub connection_count: u8,
}

fn path_point(input: &[u8]) -> IResult<&[u8], PathPoint> {
    let (input, x) = le_i32(input)?;
    let (input, y) = le_i32(input)?;
    let (input, z) = le_i32(input)?;
    let (input, flags) = le_u8(input)?;
    let (input, connection_count) = le_u8(input)?;
    let (input, _unknown) = le_u16(input)?;
    Ok((
        input,
        PathPoint {
            x,
            y,
            z,
            flags,
            connection_count,
        },
    ))
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct Pgrd<'a> {
    pub data: PathGridData,
    /// Cell name the path grid belongs to.
    pub cell: &'a L1Str,
    pub points: Vec<PathPoint>,
    /// Flattened edge list; index into `points`, grouped per point by connection count.
    pub connections: Vec<u32>,
}

impl<'a> Pgrd<'a> {
    pub fn from_subrecords(subs: &[Subrecord<'a>]) -> Pgrd<'a> {
        let mut out = Pgrd::default();
        for sub in subs {
            match &sub.tag {
                b"DATA" => out.data = parse_or_default(path_grid_data, sub.data),
                b"NAME" => out.cell = l1(sub.data),
                b"PGRP" => {
                    out.points = finish(many0(path_point).parse(sub.data)).unwrap_or_default()
                }
                b"PGRC" => {
                    out.connections = finish(many0(le_u32).parse(sub.data)).unwrap_or_default()
                }
                _ => {}
            }
        }
        out
    }
}
