//! `PGRD` — a cell path grid.

use crate::common::{finish, flags, l1, le_i32, le_u8, le_u16, le_u32, parse_or_default};
use nom::Parser;
use nom::multi::many0;
use nom::sequence::terminated;
use tes_core::L1Str;
use tes3_esm_derive::{TesPayload, TesRecord};

#[derive(Debug, Clone, Copy, PartialEq, Default, TesPayload)]
#[tes(parser = path_grid_data)]
pub struct PathGridData {
    /// Grid coordinates (exterior cells only).
    #[tes(read = le_i32)]
    pub grid_x: i32,
    #[tes(read = le_i32)]
    pub grid_y: i32,
    #[tes(read = le_u16)]
    pub flags: u16,
    #[tes(read = le_u16)]
    pub point_count: u16,
}

bitflags::bitflags! {
    /// Path grid node flags.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
    pub struct PathPointFlags: u8 {
        const AUTOGENERATED = 0x1;
    }
}

/// A single path grid node (16 bytes within `PGRP`).
#[derive(Debug, Clone, Copy, PartialEq, Default, TesPayload)]
#[tes(parser = path_point)]
pub struct PathPoint {
    #[tes(read = le_i32)]
    pub x: i32,
    #[tes(read = le_i32)]
    pub y: i32,
    #[tes(read = le_i32)]
    pub z: i32,
    #[tes(read = flags)]
    pub flags: PathPointFlags,
    /// Number of outgoing edges (entries in `PGRC` for this point).
    #[tes(read = |input| terminated(le_u8, le_u16).parse(input))]
    pub connection_count: u8,
}

#[derive(Debug, Clone, PartialEq, Default, TesRecord)]
pub struct Pgrd<'a> {
    #[tes(tag = b"DATA", decode = |bytes| parse_or_default(path_grid_data, bytes))]
    pub data: PathGridData,
    /// Cell name the path grid belongs to.
    #[tes(tag = b"NAME", decode = l1)]
    pub cell: &'a L1Str,
    #[tes(tag = b"PGRP", decode = |bytes| finish(many0(path_point).parse(bytes)).unwrap_or_default())]
    pub points: Vec<PathPoint>,
    /// Flattened edge list; index into `points`, grouped per point by connection count.
    #[tes(tag = b"PGRC", decode = |bytes| finish(many0(le_u32).parse(bytes)).unwrap_or_default())]
    pub connections: Vec<u32>,
}
